#!/usr/bin/env bash

TODAY="$(date '+%Y–%m–%d')"
if [ -z "$1" ]; then
  TITLE="Title"
else
  TITLE="$1"
fi

cat << EOF
\documentclass[12pt,a4paper]{article}

\usepackage{amsmath}
\usepackage[margin=2.5cm]{geometry}

\makeindex

\author{Bevilacqua Joey}
EOF

printf "\\\\title{$TITLE}\n\\date{$TODAY}\n"

cat << EOF

\setlength{\parindent}{0cm}
\pagestyle{plain}

\newcommand{\p}[1]{{\left(#1\right)}}

\begin{document}

\maketitle

\end{document}
EOF
